version: "3.8"

services:
    connect_source:
        container_name: connect_source
        image: debezium/connect
        build:
          context: debezium-mongodb
        ports:
         - 8083:8083
        environment:
         - BOOTSTRAP_SERVERS=kafka:9092
         - GROUP_ID=1
         - CONFIG_STORAGE_TOPIC=my_source_connect_configs
         - OFFSET_STORAGE_TOPIC=my_source_connect_offsets
    connect_sink:
        container_name: connect_sink
        image: debezium/connect-mongodb
        build:
          context: debezium-mongodb
        ports:
         - 8084:8083
        environment:
         - BOOTSTRAP_SERVERS=kafka:9092
         - GROUP_ID=2
         - CONFIG_STORAGE_TOPIC=my_sink_connect_configs
         - OFFSET_STORAGE_TOPIC=my_sink_connect_offsets
         - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
         - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false